config/routes.rb
Rails.application.routes.draw do
  get 'documentary_films/index'
  get 'documentary_films/create'
  get 'documentary_films/new'
  get 'series/index'
  get 'series/create'
  get 'series/new'
  get 'movies/index'
  get 'movies/create'
  get 'movies/new'
  resources :movies
  resources :series
  resources :documentary_films

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #root "nav"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
  end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/series.rb
class Series < ApplicationRecord
        validates :name, presence: true
        validates :synopsis, presence: true
        validates :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  def index
    @documentary_films = DocumentaryFilm.all
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)
    if @documentary_film.save
      redirect_to documentary_films_path, notice: 'El documental ha sido creado exitosamente.'
    else
      render :new
    end
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  private

  def documentary_film_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: 'La película ha sido creada exitosamente.'
    else
      render :new
    end
  end

  def new
    @movie = Movie.new
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Series.all
  end

  def create
    @series = Series.new(series_params)
    if @series.save
      redirect_to series_path, notice: 'La serie ha sido creada exitosamente.'
    else
      render :new
    end
  end

  def new
    @series = Series.new
  end

  private

  def series_params
    params.require(:series).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/create.html.erb
<h1>DocumentaryFilms#create</h1>
<p>Find me in app/views/documentary_films/create.html.erb</p>

app/views/documentary_films/index.html.erb
<h1>List of Documentary Films</h1>
<ul>
  <% @documentary_films.each do |documentary_film| %>
    <li>
      <strong>Name:</strong> <%= documentary_film.name %><br>
      <strong>Synopsis:</strong> <%= documentary_film.synopsis %><br>
      <strong>Director:</strong> <%= documentary_film.director %>
    </li>
  <% end %>
</ul>

app/views/documentary_films/new.html.erb
<h1>New Documentary Film</h1>
<%= form_with(model: @documentary_film, url: documentary_films_path) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>
  <div>
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>
  <div>
    <%= form.submit "Create Documentary Film" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pruebabasededatos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="assets/css/main.css" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<body class="is-preload">
    <%= render 'share/nav' %>
		<div id="page-wrapper">
    <%= yield %>
  </div>
    <!-- Scripts -->
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<h1>Movies</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Synopsis</th>
      <th>Director</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.synopsis %></td>
        <td><%= movie.director %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<h1>New Movie</h1>
<%= form_with(model: @movie, url: movies_path) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>
  <div>
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>
  <div>
    <%= form.submit "Create Movie" %>
  </div>
<% end %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<h1>List of Series</h1>
<ul>
  <% @series.each do |serie| %>
    <li>
      <strong>Name:</strong> <%= serie.name %><br>
      <strong>Synopsis:</strong> <%= serie.synopsis %><br>
      <strong>Director:</strong> <%= serie.director %>
    </li>
  <% end %>
</ul>

app/views/series/new.html.erb
<h1>New Serie</h1>
<%= form_with(model: @serie, url: new_series_path, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>
  <div>
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>
  <div>
    <%= form.submit "Create Serie" %>
  </div>
<% end %>

app/views/share/_nav.html.erb
<!-- Nav -->
						<nav id="nav">
							<ul>
								<li><a href="index.html">Home</a></li>
								<li>
									<a href="#">Movies</a>
									<ul>
										<li><%= link_to 'Listado', movies_index_path %></li>
										<li><%= link_to 'Ingresa nuevo', movies_new_path %></li>
									</ul>
								</li>
								<li>
									<a href="#">Series</a>
									<ul>
										<li><%= link_to 'Listado', series_index_path %></li>
										<li><%= link_to 'Ingresa nuevo', series_new_path %></li>
									</ul>
								</li><li>
									<a href="#">Documentary Films</a>
									<ul>
										<li><%= link_to 'Listado', documentary_films_index_path %></li>
										<li><%= link_to 'Ingresa nuevo', documentary_films_new_path %></li>
									</ul>
								</li>
							</ul>
						</nav>